### PR TITLE
minor code style / consistency improvements

### PR DESCRIPTION
**Pull request by mindreframer**
problem: 
- currently it's a bit mixed code style and feels like work in progress

solution: 
- puts parenthesis for function calls
- trims trailing spaces
- aligns assignment statements for better readability
- aligns function bodies for multi-signature functions
- aligns values in maps

### CODE REVIEW

**Comment by mindreframer** [comment]
Hey, 

first thanks for the EventStore client, it looks good! 
I have some local code improvements, but wanted to start with a small "spring" - cleaning. 

It would be great if we could make this client a really solid foundation for Elixir "event source" - type applications. 

Cheers!

**Comment by burmajam** [comment]
Hi Roman,

Thanks for changes. We really appreciate it. We are using this library in production for more then 6 months and are preparing one more system based on it even bigger. So far it works without any problems. However we are aware that we are not covering everything, so all PR are very welcome.

**Comment by mindreframer** [comment]
@burmajam that's great! I was afraid it is a bit vaporware, but production use is really good news! 

I like how fast the test suite is! Under 1 second! )))

**Comment by mindreframer** [comment]
@burmajam @mjaric By the way, have you thought about having a https://gitter.im channel? 

That way users can share their experience and share tips and tricks. What do you think?

**Comment by mindreframer** [comment]
Here is the gitter channel for the Haskel client: 

https://gitter.im/YoEight/eventstore

**Pull request merged**
