### PR TITLE
Fix persistent sub event processing

### PR DESCRIPTION
**Pull request by nathanfox**
I tried the persistent subscription code that was merged at commit b8bbade49f5caab8138261003ca26a4a09007e89. When I ran against a persistent subscription I received the following error:
```
** (EXIT from #PID<0.232.0>) exited in: GenServer.call(#PID<0.238.0>, {:ack, <<157, 241, 71, 42, 57, 10, 17, 231, 166, 197, 8, 0, 39, 106, 67, 158>>}, 5000)
         ** (EXIT) an exception was raised:
             ** (ArgumentError) argument error
                 :erlang.bit_size(nil)
                 (extreme) lib/request.ex:27: Extreme.Request.to_binary/4
                 (extreme) lib/request.ex:19: Extreme.Request.prepare/3
                 (extreme) lib/extreme.ex:365: Extreme.handle_call/3
                 (stdlib) gen_server.erl:615: :gen_server.try_handle_call/4
                 (stdlib) gen_server.erl:647: :gen_server.handle_msg/5
                 (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
```
I created a unit test at commit efd9f2066e562fd339c7ae71638fc2c297c51977 called *Quickly process events on persistent subscription* which reproduces the error in file [test/extreme_test.exs](https://github.com/exponentially/extreme/commit/efd9f2066e562fd339c7ae71638fc2c297c51977) line 572.

The problem seems to be that the correlation_id is kept in the PersistentSubscription module's state, but when events and acknowledgments are processed quickly, the state becomes out of sync with the event processing.

I created code at commit 095f57a1ce0e7b30eb0785498a8c0adee86d3629 which solves the issue. The correlation_id is sent to the subscriber which is then sent back with the acknowledgment, so event processing does not lose track of the correlation_id. You can see with this version of the code the test I created now passes. And the persistent subscription I have on my system now processes successfully as well.

I'm sure there might be a different way to address this issue, but this code is at least a reference and currently allows me to use the code in my system.

Please let me know if you have any questions or suggestions.

Thank you,
Nathan Fox

### CODE REVIEW

**Comment by slashdotdash** [comment]
Good catch @nathanfox. I originally implemented the persistent subscription ack following the change you've made. I then tried to hide the `correlation_id` from the subscriber by keeping it in the subscription process' state.

**Comment by nathanfox** [comment]
I'm not sure if the changes I made are desired, but I merged the latest master branch with my changes and it should now work and merge without conflict.

**Comment by burmajam** [comment]
Hi @nathanfox. I didn't use competing consumers for ES thus I can't deeply check if everything is ok. @slashdotdash created this feature so I'd like his approval for this pull request. If that's ok with him I'll merge it and push to hex this and #41

**Comment by slashdotdash** [comment]
@burmajam Looks good to me, thanks @nathanfox.

**Comment by burmajam** [comment]
I've published 0.9.1 version to hex.

Thanks guys

**Pull request merged**
